Add cli
ivanalejandro0/cabinet pull request #5
Opened 2017-03-03 21:50 UTC by facundovictor

This PR includes:

1. The first prototype for a cabinet cli.
2. A tiny typo fix on the cabinet library.

2017-03-04 02:28 UTC, ivanalejandro0 requested changes
I don't like very much the `global` approach of sharing the vault settings. I'd prefer to have a class that contains all the logic and we can instantiate once for later use on any command that the user calls.
That being said, I'd say that is not blocker anyway. Is better to have a working cli now than somehow improved one day :)
Good job!

2017-03-04 02:28 UTC, ivanalejandro0 commented on cabinet.py
> +def tuple(value):
`tuple` is a reserved word, you should use other name for this function.

2017-03-04 02:28 UTC, ivanalejandro0 commented on cabinet.py
> +            all = get_all().values()
`all` is the name of a built-in function, you should use other name.

2017-03-04 02:28 UTC, ivanalejandro0 commented on cabinet.py
> +            account_id = 'my-name@my-company.com'
either now that we are hardcoding credentials, or later that we may read some information from a config file and/or asking the user for it... we shouldn't repeat this all over the code.
I'd factor out all the credential stuff... maybe move it along `open_vault`?

2017-03-04 02:28 UTC, ivanalejandro0 commented on cabinet.py
> +        description = "Cabinet's cli client for managing valuts."
typo `s/valuts/vaults/`

2017-03-04 02:28 UTC, ivanalejandro0 commented on cabinet/cabinet.py
> +        self.add_new(name, content, tags)
good catch!

2017-03-05 17:56 UTC, facundovictor commented on cabinet.py
> +def tuple(value):
You're right, changed!

2017-03-05 17:56 UTC, facundovictor commented on cabinet.py
> +        description = "Cabinet's cli client for managing valuts."
Good catch!

2017-03-05 17:56 UTC, facundovictor commented on cabinet.py
> +            all = get_all().values()
You're right, changed.

2017-03-05 17:57 UTC, facundovictor commented on cabinet.py
> +            account_id = 'my-name@my-company.com'
Moved it inside a new class called `CabinetWrapper`.

2017-03-05 18:04 UTC, facundovictor commented
I agree on removing all global vars. For now, I've moved all to a class named `CabinetWrapper`. The idea is to have a small class that we may remove in the future by moving all the useful features to the cabinet library (if apply), some features like filtering could be required by other cabinet clients. Also, the cabinet command line should be moved to it's own repo in the future.
Glad to collaborate! =)

2017-03-05 18:05 UTC, facundovictor commented on cabinet/cabinet.py
> +        self.add_new(name, content, tags)
Thanks! I think github detects it as a requried change =P

2017-03-06 03:05 UTC, ivanalejandro0 approved these changes

2017-03-06 03:05 UTC, merged